#! /bin/bash

# ############# alias ############
if [ -e "${HOME}/.alias" ]; then
    source "${HOME}/.alias"
fi
# ################################


# ############# gvm ##############
if [[ -e "${HOME}/.gvm/scripts" ]]; then
    source ${HOME}/.gvm/scripts/gvm
fi
# ################################

# ############# nvm ##############
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# ################################

# ######### nodejs bin ###########
if [[ -e '~/node_modules/.bin' ]]; then
    export PATH="$PATH:~/node_modules/.bin"
fi
# ################################

# local custom bash/zsh rc file
if [ -e "${HOME}/.customrc" ]; then
    source "${HOME}/.customrc"
fi

# ########### ranger ############
export RANGER_LOAD_DEFAULT_RC=FALSE
# ###############################


# ########### pyenv ############
if [ `command -v pyenv` ]; then
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init -)"
    export PYENV_VIRTUALENV_DISABLE_PROMPT=1
fi
# ##############################

# ############ PATH ############
export PATH="/usr/local/sbin:/usr/local/bin:$PATH"
# ##############################

# ######### true color #########
export TERM=xterm-256color
# ##############################

# ####### tools execute ########
if [ ! -e "${HOME}/.bin" ]; then
    mkdir ${HOME}/.bin
fi
export PATH="${HOME}/.bin:$PATH"
# ##############################

