#! /bin/bash

[[ -f ~/.commonrc ]] && source ~/.commonrc
# iterm2 shell integration
[[ -f ~/.iterm2_shell_integration.bash ]] && source ~/.iterm2_shell_integration.bash
# init z.lua
eval "$(lua ~/z.lua --init bash enhanced)"
