#! /bin/bash

if ![[ -f ~/.bashrc ]]; then
    touch ~/.bashrc
fi
echo '[[ -f ~/.custom_bashrc ]] && source ~/.custom_bashrc' >> ~/.bashrc

if [[ -f ~/.bash_profile ]]; then
    echo 'source ~/.bashrc' >> ~/.bash_profile
fi
if [[ -f ~/.bash_login ]]; then
    echo 'source ~/.bashrc' >> ~/.bash_login
fi
if [[ -f ~/.profile ]]; then
    echo 'source ~/.bashrc' >> ~/.profile
fi

if [[ ! -f ~/.zshrc ]]; then
    touch ~/.zshrc
fi
echo '[[ -f ~/.custom_zshrc ]] && source ~/.custom_zshrc' >> ~/.zshrc
